dndWeb:
  image: erikap/ruby-sinatra
  ports:
   - "8443:8443"
  volumes:
   - "./web:/usr/src/app"
  env_file:
   - ./environment
  links:
   - mongo
mongo:
  image: mongo:3.0
  ports:
   - "27017:27017"
  env_file:
   - ./environment
  volumes:
   - "./mongodb:/data/db"