dndWeb:
  image: erikap/ruby-sinatra
  ports:
   - "8443:8443"
  volumes:
   - "./web:/usr/src/app"
  env_file:
   - ./environment
  links:
   - couchdb
couchdb:
  image: tutum/couchdb
  ports:
   - "5984:5984"
  env_file:
   - ./environment
  volumes:
   - "./couchdb:/var/lib/couchdb"