frontend:
  image: semtech/mu-nginx-spa-proxy
  volumes:
    - ./client/dist:/app
    - ./config/nginx:/etc/nginx/conf.d/
  links:
    - identifier:backend
  ports:
    - "80:80"
identifier:
  image: semtech/mu-identifier
  links:
    - dispatcher:dispatcher
dispatcher:
  image: semtech/mu-dispatcher
  links:
    - resource:resource
    - registration:registration
    - login:login
  volumes:
    - ./config:/config
db:
  image: tenforce/virtuoso:virtuoso-v7.2.0-latest
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://mu.semte.ch/application"
  volumes:
    - ./data/virtuoso:/var/lib/virtuoso/db
  ports:
    - "8890:8890"
resourcebackend:
  image: "semtech/mu-cl-resources:1.12.4"
  links:
    - db:database
  volumes:
    - ./config/resources:/config
  environment:
    BOOT: mu-cl-resources
resource:
  image: "semtech/mu-cache:0.1.0"
  links:
    - resourcebackend:backend
  environment:
    CACHE_BACKEND: "http://backend"
registration:
  image: semtech/mu-registration-service:2.4.0
  links:
    - db:database
  environment:
    MU_APPLICATION_SALT: "KteCAqj7bAjEavWhUhUHL4oPFc3ePvVVMKgHKoh7nTqAvhRuatxoTkpnePrLPiWk"
    MU_AUTO_LOGIN_ON_REGISTRATION: "true"
login:
  image: semtech/mu-login-service:2.5.0
  links:
    - db:database
  environment:
    MU_APPLICATION_GRAPH: "http://mu.semte.ch/application"
    MU_APPLICATION_SALT: "KteCAqj7bAjEavWhUhUHL4oPFc3ePvVVMKgHKoh7nTqAvhRuatxoTkpnePrLPiWk"
