(in-package :mu-cl-resources)

(setf *supply-cache-headers-p* t)

(define-resource character ()
  :class (s-prefix "dnd:Character")
  :features '(no-pagination-defaults)
  :properties `((:name :string ,(s-prefix "foaf:name"))
               (:level :number ,(s-prefix "dnd:level"))
               (:race :string ,(s-prefix "dnd:race"))
               (:class-name :string ,(s-prefix "dnd:class"))
               (:description :string ,(s-prefix "dcterms:description")))
  :resource-base (s-url "http://dnd.semte.ch/characters/")
  :has-one `((player :via ,(s-prefix "dnd:player")
                    :as "player"))
  :has-many `((item :via ,(s-prefix "dnd:hasItem")
                    :as "items")
             (spell :via ,(s-prefix "dnd:hasSpell")
                     :as "spells"))
  :on-path "characters")

(define-resource player ()
  :class (s-prefix "dnd:Player")
  :features '(no-pagination-defaults)
  :properties `((:name :string ,(s-prefix "foaf:name"))
               (:description :string ,(s-prefix "dcterms:description")))
  :resource-base (s-url "http://dnd.semte.ch/players/")
  :has-many `((players :via ,(s-prefix "dnd:player")
                      :inverse t
                      :as "characters"))
  :on-path "players")


(define-resource item ()
  :class (s-prefix "dnd:Item")
  :features '(no-pagination-defaults)
  :properties `((:name :string ,(s-prefix "dct:title"))
               (:weight :number ,(s-prefix "dnd:weight"))
               (:price :number ,(s-prefix "dnd:price"))
               (:description :string ,(s-prefix "dcterms:description")))
  :resource-base (s-url "http://dnd.semte.ch/items/")
  :on-path "items")

(define-resource spell ()
  :class (s-prefix "dnd:Spell")
  :features '(no-pagination-defaults)
  :properties `((:name :string ,(s-prefix "dct:title"))
               (:description :string ,(s-prefix "dcterms:description"))
               (:level :number ,(s-prefix "dnd:spellLevel"))
               (:origin :string ,(s-prefix "dnd:spellOrigin"))
               (:school :string ,(s-prefix "dnd:spellSchool"))
               (:action :string ,(s-prefix "dnd:action"))
               (:range :string ,(s-prefix "dnd:range"))
               (:components :string ,(s-prefix "dnd:components"))
               (:duration :string ,(s-prefix "dnd:duration"))
               (:ritual :boolean ,(s-prefix "dnd:isRitual")))
  :resource-base (s-url "http://dnd.semte.ch/spells/")
  :on-path "spells")

